# DATABASE CONFIG
DATABASE:
  DB_HOST: 127.0.0.1
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  DB_NAME: "ecommerce"
  DB_PORT: 5432
  DB_SSL: "disable"
  DB_SET_MAX_OPEN_CONN: 10
  DB_SET_IDLE_CONN: 5
  DB_CONN_MAX_LIFE_TIME: 10

# APP CONFIG
APP_PORT: "5004"
APP_READ_TIME_OUT: 30
APP_WRITE_TIME_OUT: 30
JWT_SECRET_KEY: "b7dafe06d41d764ed6b1a325ffde7b7dafe06d41sbc"

# ASSETS CONFIG
LOGS_DIR: "assets/logs/"