# DATABASE CONFIG
DATABASE:
  DB_HOST: 0
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  DB_PORT: 0
  DB_SSL: ""
  DB_SET_MAX_OPEN_CONN: 0
  DB_SET_IDLE_CONN: 0
  DB_CONN_MAX_LIFE_TIME: 0

# APP CONFIG
APP_PORT: ""
APP_READ_TIME_OUT: 0
APP_WRITE_TIME_OUT: 0

# ASSETS CONFIG
LOGS_DIR: ""